### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by modem7** [ddworken/hishtory#128]
Heya, 

I'm attempting to use sqlite on the LSIO docker image, but I'm having a couple of issues where it doesn't seem to be doing anything with the sqlite file.

```yaml
  hishtory-server:
    image: lscr.io/linuxserver/hishtory-server:latest
    container_name: Hishtory-Server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - HISHTORY_SQLITE_DB=/sqlite/db.sqlite
      # - HISHTORY_POSTGRES_DB=postgresql://${HISHTORY_DB_USER}:${HISHTORY_DB_PASS}@localhost:5432/hishtory?sslmode=disable
    network_mode: "host"
#    ports:
#      - 24244:8080
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/HishtoryDB:/sqlite/
    # depends_on:
      # - hishtory-db
    restart: always
```

The message I get in the logs is:

`No database configured, sleeping...`

This is probably an ID10T issue.
